### ISSUE TITLE
Missing File: Volvo-DataX/datax_volvo_additional_files/yolov3_train_5.tf.data-00001-of-00002

### ISSUE THREAD

**Issue by gaozhunbj** [mjpramirez/Volvo-DataX#6]
I am encountering an issue when attempting to load weights for the YOLO model in the Volvo-DataX project. The specific error message I receive indicates that a required file is missing：
```
tensorflow.python.framework.errors_impl.NotFoundError: Volvo-DataX/datax_volvo_additional_files/yolov3_train_5.tf.data-00001-of-00002; No such file or directory [Op:RestoreV2]
```
Clone the repository and navigate to the project directory.
Attempt to load the model weights using the following code:
yolo.load_weights("datax_volvo_additional_files/yolov3_train_5.tf").expect_partial()
Observe the error indicating the missing file.
Expected Behavior: The weights should load successfully without any missing file errors.

Observed Behavior: The process fails with a NotFoundError, specifically indicating that the file yolov3_train_5.tf.data-00001-of-00002 is missing.

The provided Google Drive link for downloading the files is missing yolov3_train_5.tf.data-00001-of-00002.

**Comment by AsangCode** [comment]
@gaozhunbj : Hi, I am also facing the same issue. Were you able to get the missing files?
